### ISSUE TITLE
sentence-case is huge

### ISSUE THREAD

**Issue by refractalize** [bendrucker/creditcards#12]
Hi,

Love the lib - but it depends on `camel-case` which depends on `sentence-case` which is somehow very large (15kB minified). I think it's to do with supporting extended unicode character sets. We like to keep our JS downloads small.

I've tracked the dependency down to this:

https://github.com/bendrucker/creditcards/blob/master/src/types.js#L9

Which seems fairly innocent. Do you think we can write our own miniature "camelCase" to do this, without dragging in sentence case, etc? I'm quite happy to make a pull request, but wanted to know exactly what you were doing with the camel case bit.

I'm assuming that you want `card.isValid(number, 'Master Card')` to work? So things like "VISA", "Master Card" etc get turned into "visa" and "masterCard" right? Anything else?

As I said, happy to make a PR if you give me a nod.

**Comment by bendrucker** [comment]
Good catch, let's totally replace that! I'll take care of it and make sure some of the dependent libs of creditcards work.

**Comment by bendrucker** [comment]
![screenshot](http://d.pr/i/1ai2V+)
