### ISSUE TITLE
method to validate the whole card

### ISSUE THREAD

**Issue by stepanzarubin** [bendrucker/creditcards#22]
is there method to validate the whole CC data? e.g.:

```
cc = {
   number: '1234567876',
   expire: '02/17',
   cvc: '123'
}

function isCCValid(number, expire, cvc) {
    ...
   //validate all the fields and make sure that it is still active by expire field
}
```

it is not clear how to implement one, documentation on `isValid` is not clear since there is no description for some of them, will `expiration.month.isValid` check only format or will also check the past month?

**Comment by bendrucker** [comment]
There is no function for all the data. None of the fields are tightly related so the functions aren't coupled either. If you want to check for an expiration date that's passed, see https://github.com/bendrucker/creditcards#ispastmonth-year---boolean.

This library is designed for the actual challenges you'd run into when designing high quality (i.e. specific) validation messages for a server or UI. When you combine all the checks into a single function you lose the ability to provide a specific error message.

If you think documentation could be clearer for a specific function *in isolation*, please send a PR and we can discuss a specific request. 

You've answered your own question:

> expiration.month.isValid check only format or will also check the past month

How would a month checker know that `1` is a past month (1/17) versus a future one? It can't, so it's just validating 

Validation is best done progressively!
