### ISSUE TITLE
FR: Add placeholder support for format

### ISSUE THREAD

**Issue by dev054** [bendrucker/creditcards#39]
Proposed signature:

`card.format(number, [separator], [placeholder]) -> string`

Examples:

Input: `card.format(5277, ' ', '•')`
Output: 5277 •••• •••• ••••

As an example you can see this: https://ovvwzkzry9.codesandbox.io, as you type the field is formatted and the placeholder (•), for unfilled characters, is maintained.

**Comment by bendrucker** [comment]
Will happily take a PR for this

**Comment by bendrucker** [comment]
Closing based on lack of response and interest
