### ISSUE TITLE
credit card type not being updated on the model if specified in data-cc-type

### ISSUE THREAD

**Issue by owlyowl** [bendrucker/creditcards#7]
Hi Ben,
I was wondering how could I pass the credit card type up to my model I've tried:
<input type="text" class="input-text" id="cardNumber" data-cc-number name="cardNumber" data-cc-type="payment.creditCardType" data-ng-model="payment.creditCardNumber">

But payment.creditCardType isn't updated?
Thanks

**Comment by bendrucker** [comment]
Need more info than this. I don't understand what you're asking

**Comment by bendrucker** [comment]
Also this is on the wrong repo

**Comment by owlyowl** [comment]
All good that was an error between chair and keyboard

On 18 February 2015 at 23:38, Ben Drucker <notifications@github.com> wrote:

> Closed #7 <https://github.com/bendrucker/creditcards/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bendrucker/creditcards/issues/7#event-237621731>.
>



-- 
Tom Fulcher
Creative Designer and Developer

[image: Envoy]

Envoy Advanced Technologies Pty Ltd
Level 1, 194 Miller St, North Sydney NSW 2060

Mobile Apps | Software Development | Custom Applications | Fully Managed
Hosting

http://www.envoyat.com | m: 0403 316 714 | p: +61 2 8097 7328 | skype:
thomen12

---------------------------------------------------------------------------------
This email and any attachment is only intended for the use of the
individuals or entities to whom it is addressed and may contain
confidential, privileged information. If the reader of this information is
not the addressee, please be advised that any dissemination, distribution
or copying of this email is strictly prohibited. If you receive this
communication in error, please return this email to Envoy Advanced
Technologies at the above email address and delete it from your files.
Thank you.

**Comment by bendrucker** [comment]
:)
