### ISSUE TITLE
Let cvc be a number

### ISSUE THREAD

**Issue by jrencz** [bendrucker/creditcards#8]
I use this library wrapped with angular-credit-cards and I found one problem: I apply cvc validator to a field of type "number".

If input has `type="number"` then the value is parsed and a number goes to the validator.
It's worth using `type="number"` to get numerical keyboard on mobile devices.

I suggest number to pass as well.

**Comment by jrencz** [comment]
Ok, my bad. This is an angular thing that model is parsed.

**Comment by bendrucker** [comment]
Happy to discuss the angular-credit-cards but creditcards should definitely be strict about this
